# Generated by Django 4.1.2 on 2022-10-06 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 19, 33, 557851)),
        ),
    ]
