# Generated by Django 4.1.2 on 2022-10-12 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=5)),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 10, 12, 11, 55, 17, 485317))),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 11, 55, 17, 485317)),
        ),
    ]
